# Generated by Django 3.0.3 on 2020-02-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hit_points', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('resistances', models.CharField(max_length=280)),
                ('immunities', models.CharField(max_length=280)),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
